backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
collections:
  - name: "post"
    label: "Post"
    folder: "site/content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body. name: "body", widget: "markdown"}
